name: Tests Ubuntu

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Step 2: Install dependencies (if required)
    # (Install build-essential which includes gcc, make, etc.)
    - name: Install dependencies
      run: sudo apt-get install build-essential

    # Step 3: Compile the project using make
    - name: Build project
      run: make

    # Step 4: Run the compiled executable
    - name: Run executable
      run: ./project
